import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";
import ChatBtn from "@/components/ui/ChatBtn";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable}  h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <main>
          <Header />
           <ChatBtn />
             <ClerkProvider>
        {children}
             </ClerkProvider>
        <Footer />
              <Toaster />
        </main>
        </body>
    </html>
  );
}
